### ISSUE TITLE
ANSI color escape sequences in logs

### ISSUE THREAD

**Issue by lcheylus** [yodamad/heimdall#10]
When I'm using heimdall to check my Git directories, there are some ANSI color escape sequence in logs (`heimdall.log` file as default).

Example with my Git directories in `/home/fox/dev/`: `heimdall -r /home/fox/dev git-info`

`heimdall.log`:
```
time="2024-10-01T07:23:43+02:00" level=info msg="Searching in \x1b[94m'/home/fox/dev/'\x1b[39m ...\x1b[0m"
time="2024-10-01T07:23:48+02:00" level=warning msg="Cannot fetch /home/fox/dev/archey4-ports.git. Skip it... (authentication required)"
time="2024-10-01T07:23:48+02:00" level=info msg="  \x1b[93mError analyzing \x1b[94m/home/fox/dev/archey4-ports.git\x1b[93m, skip it...\x1b[0m"
(...)
```

It would be better if logs saved in text file don't contain ANSI color escape sequences.

**Comment by yodamad** [comment]
Thank you, I'll have a look
