### ISSUE TITLE
📦  Publishing module/project on pkg.go.dev

### ISSUE THREAD

**Issue by lcheylus** [yodamad/heimdall#8]
I would like to package your great tool/project for OpenBSD.

The port infrastructure for OpenBSD is based on Makefile and needs to get sources and Go modules (dependencies for heimdall) from https://pkg.go.dev (via Go proxy).

Could you please publish your project and future releases on https://pkg.go.dev ?

HOWTO "Publishing a module" https://go.dev/doc/modules/publishing

**Comment by yodamad** [comment]
@lcheylus whaou ! OK I'll try to do that for v1.
I need to finalize and stabilize some features first I think, but for sure I'll have a look to do that

**Comment by yodamad** [comment]
@lcheylus : Mechanism is implemented, it'll be publish in next release under `github.com/yodamad/heimdall`

**Comment by lcheylus** [comment]
Thanks, heimdall project is now published on pkg.go.dev => https://pkg.go.dev/github.com/yodamad/heimdall :)

**Comment by yodamad** [comment]
Hum weird stuff regarding the version 😕 
I've to fix this and to improve the code documentation 😅

**Comment by yodamad** [comment]
@lcheylus let me know if you face any problem to package it into OpenBSD

**Comment by yodamad** [comment]
Publishing on pkg.go.dev fixed
