### ISSUE TITLE
🫧 Replace term module by charmbracelet/bubbles

### ISSUE THREAD

**Issue by lcheylus** [yodamad/heimdall#9]
To display menu (source in `utils/menu.go`), your project uses `github.com/pkg/term` Go module. This module is old and not well supported on some OS (especially on BSD ones).

Could you replace use of `term` module by another one? Bubbles by charmbracelet is a good candidate: a lot of TUI components for Go and simple to use => https://github.com/charmbracelet/bubbles

**Comment by yodamad** [comment]
@lcheylus : yes I discovered bubbles yesterday 😉 https://x.com/yodamad03/status/1839705592874598571

This is one of my next tasks to switch to bubbles 😄

**Comment by yodamad** [comment]
`xterm` removed 

`Input` & `single choice` switched to bubbles

Remains the `multi choice` for `git pull` option

**Comment by yodamad** [comment]
Fix in https://github.com/yodamad/heimdall/releases/tag/0.2.0
